version: '3'
services:
  php:
    image: php:7.4-fpm
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  postgresql:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=root




