
- hosts: ubuntu
  tasks:
    - name: Run the equivalent of apt-get update
      apt:
        update_cache: yes
 
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
 
    - name: postgrs
      apt:
        name: pgsql
        state: latest
 
    - name: Install PHP-FPM
      apt:
        name: php-fpm
        state: latest
 
    - name: Install module PHP-psgql
      apt:
        name: php5-pgsql
        state: latest